### PR TITLE
Tweak wording in labels file

### PR DESCRIPTION
**Pull request by ee7**
Another alternative for
> point users to things they can help contribute with

is:

> point users to things they can help with

### CODE REVIEW

**Comment by ee7** [comment]
While I'm here... this line ends with "working on the issue":

https://github.com/exercism/org-wide-files/blob/2b6aa296713995bfe43de696432fc65254606b66/global-files/.github/labels.yml#L22

but labels can be applied to both issues and PRs, right? So "working on an issue" might communicate "labels can only be applied to issues" - a PR might not have a corresponding issue.

So perhaps

> when working on the issue/PR 

---

And consider whether

https://github.com/exercism/org-wide-files/blob/2b6aa296713995bfe43de696432fc65254606b66/global-files/.github/labels.yml#L10

starts better as e.g.:

> ```
> # If either file is changed,
> ```

I find it's often clearer to prefer the singular in technical writing.

**Comment by ErikSchierboom** [comment]
Sooo...I like these changes, but I wouldn't necessarily want to send another batch of PRs right now. So either we:

- Leave this PR open for a while
- Merge this and cancel the workflow

Right @SaschaMann?

**Comment by SaschaMann** [comment]
This isn't worth sending out 300 PRs imo. We can merge it with `[ci skip]` in the message and then it'll be synced during the next batch automatically.

**Comment by ErikSchierboom** [comment]
@SaschaMann Can you merge it?

**Review by SaschaMann — APPROVED** [review]

**Comment by SaschaMann** [comment]
Thanks, @ee7 :)

**Comment by ee7** [comment]
No problem.

Quick questions about labels - sorry if I missed the discussion:
- Is there an official stance on whether an Exercism-wide label should be applied to a PR? Do we let repos decide?
- Does a PR with such a label appear on the website? (I assume the answer is "no", and [the docs](https://github.com/exercism/docs/blob/main/product/tasks.md) seem to indicate that).

**Comment by ErikSchierboom** [comment]
> Is there an official stance on whether an Exercism-wide label should be applied to a PR? Do we let repos decide?

We do. The official labels _are_ required if a track want to modify the experience gained from a PR: https://github.com/exercism/docs/blob/main/product/reputation.md#4-creating-pull-requests

> Does a PR with such a label appear on the website? (I assume the answer is "no", and the docs seem to indicate that).

They don't.

**Comment by ee7** [comment]
Okay, thanks.

Some more:
- If a PR lacks an `x:size` label, but closes an issue that does have an `x:size` label, does the issue label determine the awarded reputation?
- If yes, what happens if a PR closes multiple issues, but has no reputation label itself?
- If the `x:size` label on an issue is different from the `x:size` label on the PR, does the label with the highest reputation value determine the awarded reputation? Or is it just the label on the PR with the highest reputation value?

The docs say:
> The reputation awarded for a pull request review changes if one of the following labels are added to the pull request

> If more than one label is specified, the label with the highest reputation value determines the awarded reputation.

Which suggests "only the label on the PR matters" - correct? It's just that it seems easy to forget to apply the label to the PR, given that applying it to the issue makes the size searchable on the website.

(Again, sorry if this was already discussed, or is on a roadmap somewhere).

**Comment by ErikSchierboom** [comment]
> Which suggests "only the label on the PR matters" - correct? It's just that it seems easy to forget to apply the label to the PR, given that applying it to the issue makes the size searchable on the website.

That is correct. There is indeed a possibility for forgetting to apply the size label on a PR, so that's unfortunately a burden on the maintainers.

**Pull request merged**
